### ISSUE TITLE
Refrescar lista de reclamos cuando se crea un nuevo reclamo

### ISSUE THREAD

**Issue by dcorvetto** [yair-code/TpAppInteractivas#29]
(consultar si se necesita patron observador o si se puede manejar con un timer)

**Comment by cintainfinita** [comment]
esto no lo entiendo. la lista de los reclamos aparece cuando vamos a ver los reclamos. el hecho de crear uno nuevo esta en otra ventana y la de ver no esta visible. cuando creamos uno y vamos a ver los reclamos, ahi se muestra y ya aparece el nuevo.... :S

**Comment by cintainfinita** [comment]
para que quede: use esto de ejemplo http://migranitodejava.blogspot.com.ar/2011/06/observer.html
